### ISSUE TITLE
Errors in print

### ISSUE THREAD

**Issue by liu-xiao-guo** [jospdeleon/elasticats#1]
I tried to run the application using Python 3.11.8, I found the following two lines of codes in the app.py (line 106) has an error, and after changing it to the following, it becomes OK

` print (f"Search query: {search_params['query']}")`
 
The same error happens to the line 113. I changed it to be the following:

`print(f"Total results: {results['hits']['total']['value']}")`

**Comment by jospdeleon** [comment]
I merged the suggested fixes in PR #2. Thank you for reporting it!
